# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.11.7
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - ximagination80@gmail.com
jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

after_success:
  - sbt "project Comparator" coverageReport

