# See http://about.travis-ci.org/docs/user/build-configuration/
sudo: false # Enable new travis container-based infrastructure

language: scala

scala:
   - 2.10.5
   - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - ximagination80@gmail.com

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - codecov
  - sbt "project comparator" coverageReport