language:
  - scala

scala:
  - 2.9.3
  - 2.10.5
  - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - ximagination80@gmail.com

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - codecov
  - sbt "project comparator" coverageReport


# See http://about.travis-ci.org/docs/user/build-configuration/